{
	"version": 1702963238,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background_green.png",
		"images/builder_background01.png",
		"images/coins-sheet0.png",
		"images/coins-sheet1.png",
		"images/coins-sheet2.png",
		"images/builder02.png",
		"images/portal_visual-sheet0.png",
		"images/portal_visual-sheet1.png",
		"images/portal_visual-sheet2.png",
		"images/boxing_punch-sheet0.png",
		"images/boxing_punch-sheet1.png",
		"images/boxing_punch-sheet2.png",
		"images/ball_indicator-sheet0.png",
		"images/ball_indicator-sheet1.png",
		"images/ball_indicator-sheet2.png",
		"images/impulses-sheet0.png",
		"images/particles_color1.png",
		"images/particles_color2.png",
		"images/particles_color3.png",
		"images/particles_color4.png",
		"images/hole-sheet0.png",
		"images/touch_area-sheet0.png",
		"images/target_control-sheet0.png",
		"images/target_indicator_spawn-sheet0.png",
		"images/distance_control.png",
		"images/target_indicator-sheet0.png",
		"images/target_indicator-sheet1.png",
		"images/show_target_indicator.png",
		"images/cancel_button-sheet0.png",
		"images/touch_indicator-sheet0.png",
		"images/touch_indicator-sheet1.png",
		"images/touch_indicator-sheet2.png",
		"images/boxing_glove-sheet0.png",
		"images/boxing_glove-sheet1.png",
		"images/spike_bar.png",
		"images/effect_ball_explosion-sheet0.png",
		"images/effect_coins_collect-sheet0.png",
		"images/coins_shadow-sheet0.png",
		"images/coins_shadow-sheet1.png",
		"images/coins_shadow-sheet2.png",
		"images/effect_smoke_trail-sheet0.png",
		"images/effect_smoke_trail-sheet1.png",
		"images/effect_smoke_trail-sheet2.png",
		"images/portal_light-sheet0.png",
		"images/cannon-sheet0.png",
		"images/cannon-sheet1.png",
		"images/burners-sheet0.png",
		"images/burners-sheet1.png",
		"images/play_button-sheet0.png",
		"images/loading_bar_background-sheet0.png",
		"images/loading_bar.png",
		"images/loadin_text-sheet0.png",
		"images/audio_button-sheet0.png",
		"images/audio_button-sheet1.png",
		"images/portal-sheet0.png",
		"images/ball-sheet0.png",
		"images/effect_ball_trail-sheet0.png",
		"images/effect_ball_trail-sheet1.png",
		"images/sand-sheet0.png",
		"images/movement_blocks-sheet0.png",
		"images/flag-sheet0.png",
		"images/pause_button-sheet0.png",
		"images/pause_button-sheet1.png",
		"images/cannon_target_spawn-sheet0.png",
		"images/movement_map-sheet0.png",
		"images/new_position-sheet0.png",
		"images/water_tiles-sheet0.png",
		"images/water_tiles-sheet1.png",
		"images/color_transition-sheet0.png",
		"images/mole_hole-sheet0.png",
		"images/collision_mask.png",
		"images/effect_cannon_explosion-sheet0.png",
		"images/effect_cannon_explosion-sheet1.png",
		"images/effect_cannon_explosion-sheet2.png",
		"images/ball_shadow-sheet0.png",
		"images/hill-sheet0.png",
		"images/hill-sheet1.png",
		"images/hill_overlay-sheet0.png",
		"images/hill_left_recoil-sheet0.png",
		"images/hill_right_recoil-sheet0.png",
		"images/hill_set_curve-sheet0.png",
		"images/exit_button_menu-sheet0.png",
		"images/restart_button-sheet0.png",
		"images/information_background.png",
		"images/coins_textgreen.png",
		"images/score_textgreen.png",
		"images/bestscore_textgreen.png",
		"images/cannon_shadow-sheet0.png",
		"images/cannon_shadow-sheet1.png",
		"images/builder01-sheet0.png",
		"images/builder01-sheet1.png",
		"images/builder01-sheet2.png",
		"images/builder_background02.png",
		"images/block_style-sheet0.png",
		"images/block_style-sheet1.png",
		"images/flag_shadow-sheet0.png",
		"images/flag_shadow-sheet1.png",
		"images/screen_background-sheet0.png",
		"images/vegetation.png",
		"images/screen_title-sheet0.png",
		"images/screen_overlay.png",
		"images/ui_flag-sheet0.png",
		"images/ui_ball-sheet0.png",
		"images/vegetation_shadow.png",
		"images/menu_backgroud.png",
		"images/menu_overlay_background-sheet0.png",
		"images/menu_vegetation.png",
		"images/menu_clouds.png",
		"images/gametitle-sheet0.png",
		"images/menu_mill-sheet0.png",
		"images/mill_propeller-sheet0.png",
		"images/mill_propeller_shadow-sheet0.png",
		"images/mill_propeller_shadow-sheet1.png",
		"images/game_version_text-sheet0.png",
		"images/ui_title_flag-sheet0.png",
		"images/ui_title_flag-sheet1.png",
		"images/gametitle_background-sheet0.png",
		"images/buttons_background-sheet0.png",
		"images/loading_bar_ball-sheet0.png",
		"images/loading_bar_overlap-sheet0.png",
		"images/particles_color5.png",
		"images/loading_bar_flag-sheet0.png",
		"images/loading_bar_flag-sheet1.png",
		"images/tutorial_element_hand-sheet0.png",
		"images/tutorial_element_text-sheet0.png",
		"images/tutorial_element_indicator-sheet0.png",
		"images/tutorial_element_indicator-sheet1.png",
		"images/background_blue.png",
		"images/builder05-sheet0.png",
		"images/builder05-sheet1.png",
		"images/score_textblue.png",
		"images/bestscore_textblue.png",
		"images/coins_textblue.png",
		"images/guide_background.png",
		"images/mill-sheet0.png",
		"images/mill_shadow-sheet0.png",
		"images/lighthouse_floor-sheet0.png",
		"images/lighthouse_floor-sheet1.png",
		"images/lighthouse_floor-sheet2.png",
		"images/water_tiles_deck-sheet0.png",
		"images/builder04-sheet0.png",
		"images/builder04-sheet1.png",
		"images/effect_ball_colision-sheet0.png",
		"images/effect_ball_colision-sheet1.png",
		"images/effect_ball_colision-sheet2.png",
		"images/shake_screen-sheet0.png",
		"images/impulses_shadow.png",
		"images/sand_shadow.png",
		"images/burners_shadow.png",
		"images/builder03-sheet0.png",
		"images/builder03-sheet1.png",
		"images/builder03-sheet2.png",
		"images/builder06-sheet0.png",
		"images/builder06-sheet1.png",
		"images/scroll_screen-sheet0.png",
		"media/ball collision 1.ogg",
		"media/ball collision 2.ogg",
		"media/ball drop.ogg",
		"media/impulse.ogg",
		"media/ball explosion.ogg",
		"media/cannon.ogg",
		"media/coin.ogg",
		"media/boxing glove.ogg",
		"media/portal.ogg",
		"media/active element 1.ogg",
		"media/restart button.ogg",
		"media/burned ball.ogg",
		"media/ui sound.ogg",
		"media/checked hole.ogg",
		"media/tiles collision.ogg",
		"media/water splash.ogg",
		"media/ui buttons.ogg",
		"media/active element 2.ogg",
		"media/touch sound 1.ogg",
		"media/touch sound 2.ogg",
		"media/sand.ogg",
		"media/mole.ogg",
		"media/birds sound.ogg",
		"media/sea sound.ogg",
		"media/main music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}